name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.1", "7.2", "7.3", "7.4"]
        service: [php-fpm, php-worker, workspace, laravel-horizon]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        PHP_VERSION: ${{ matrix.php_version }}
      run: |
        cp env-example .env
        docker-compose build ${{ matrix.service }}
